"""Plot training curves from the CSV logs generated by train.py."""

import argparse
import csv
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


def plot_training_curves(csv_path, output_path=None, window=100):
    """Create a PNG summary plot for one training CSV log."""
    csv_path = Path(csv_path)
    output_path = Path(output_path) if output_path is not None else csv_path.with_suffix(".png")

    rows = _read_rows(csv_path)
    if not rows:
        raise ValueError(f"No plottable episode rows found in {csv_path}")

    steps = [row["step"] for row in rows]
    returns = [row["episode_return"] for row in rows]
    success = [row["success"] for row in rows]

    extra_panels = []
    if all("epsilon" in row for row in rows):
        extra_panels.append(("Epsilon", [row["epsilon"] for row in rows], "tab:purple"))

    loss_rows = _read_loss_rows(csv_path)
    panel_count = 3 + bool(extra_panels) + bool(loss_rows)
    fig, axes = plt.subplots(panel_count, 1, figsize=(10, 2.8 * panel_count), sharex=False)
    if panel_count == 1:
        axes = [axes]

    axes[0].plot(steps, returns, color="tab:blue", linewidth=1.2)
    axes[0].plot(steps, _rolling_mean(returns, window), color="tab:orange", linewidth=2.0)
    axes[0].set_title("Episode Return")
    axes[0].set_ylabel("Return")
    axes[0].grid(alpha=0.3)

    axes[1].plot(steps, _rolling_mean(success, window), color="tab:green", linewidth=2.0)
    axes[1].set_title(f"Success Rate (rolling {window})")
    axes[1].set_ylabel("Success")
    axes[1].set_ylim(-0.05, 1.05)
    axes[1].grid(alpha=0.3)

    axes[2].plot(steps, [row["episode_length"] for row in rows], color="tab:red", linewidth=1.2)
    axes[2].plot(
        steps,
        _rolling_mean([row["episode_length"] for row in rows], window),
        color="tab:brown",
        linewidth=2.0,
    )
    axes[2].set_title("Episode Length")
    axes[2].set_ylabel("Steps")
    axes[2].grid(alpha=0.3)

    axis_index = 3
    for title, values, color in extra_panels:
        axes[axis_index].plot(steps, values, color=color, linewidth=1.6)
        axes[axis_index].set_title(title)
        axes[axis_index].grid(alpha=0.3)
        axis_index += 1

    if loss_rows:
        loss_steps = [row["step"] for row in loss_rows]
        axes[axis_index].plot(
            loss_steps,
            [row["policy_loss"] for row in loss_rows],
            label="Policy loss",
            color="tab:cyan",
            linewidth=1.4,
        )
        axes[axis_index].plot(
            loss_steps,
            [row["value_loss"] for row in loss_rows],
            label="Value loss",
            color="tab:pink",
            linewidth=1.4,
        )
        axes[axis_index].set_title("PPO Losses")
        axes[axis_index].legend()
        axes[axis_index].grid(alpha=0.3)

    for axis in axes:
        axis.set_xlabel("Environment Step")

    fig.suptitle(csv_path.stem, fontsize=14)
    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=160)
    plt.close(fig)
    return output_path


def _read_rows(csv_path):
    rows = []
    with Path(csv_path).open(newline="") as file:
        for row in csv.DictReader(file):
            if not row.get("episode_return"):
                continue
            rows.append(
                {
                    "step": int(float(row["step"])),
                    "episode_return": float(row["episode_return"]),
                    "episode_length": float(row["episode_length"]),
                    "success": float(row["success"]),
                    **_optional_float(row, "epsilon"),
                }
            )
    return rows


def _read_loss_rows(csv_path):
    rows = []
    with Path(csv_path).open(newline="") as file:
        for row in csv.DictReader(file):
            if not row.get("policy_loss") or not row.get("value_loss"):
                continue
            rows.append(
                {
                    "step": int(float(row["step"])),
                    "policy_loss": float(row["policy_loss"]),
                    "value_loss": float(row["value_loss"]),
                }
            )
    return rows


def _optional_float(row, key):
    if key not in row or row[key] == "":
        return {}
    return {key: float(row[key])}


def _rolling_mean(values, window):
    if window <= 1:
        return values

    means = []
    running_sum = 0.0
    for index, value in enumerate(values):
        running_sum += value
        if index >= window:
            running_sum -= values[index - window]
        means.append(running_sum / min(index + 1, window))
    return means


def main():
    parser = argparse.ArgumentParser(description="Plot training curves from a train.py CSV log")
    parser.add_argument("csv_path", help="Path to a CSV log generated by train.py")
    parser.add_argument("--output", default=None, help="Output PNG path. Defaults to CSV path with .png suffix")
    parser.add_argument("--window", type=int, default=100, help="Rolling average window")
    args = parser.parse_args()

    output_path = plot_training_curves(args.csv_path, args.output, args.window)
    print(f"Saved plot to {output_path}")


if __name__ == "__main__":
    main()
